version: '3'
services:
  mysql-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    networks:
      - swarada-network
  server-container:
    build:
      context: .
      dockerfile: dockerfile
    image: swarada-nodeform
    ports:
      - '5000:5000'
    networks:
      - swarada-network
    depends_on:
      - mysql-server

networks:
  swarada-network:
    driver: bridge
